<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>c9d8bdc9-bad8-46e0-ba02-287c1d1f00c1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Presentation\macchiato.client\macchiato.client.esproj" />
    <ProjectReference Include="..\Presentation\Macchiato.Server\Macchiato.Server.csproj" />
  </ItemGroup>

</Project>
